### ISSUE TITLE
take a look

### ISSUE THREAD

**Issue by iddoeldor** [NorthwaveNL/fridax#6]
https://github.com/iddoeldor/mplus

BTW, very nice logo ! 

Remove the "X" and give it to Frida :)

**Comment by tijme** [comment]
Hi @iddoeldor,

Thanks for the compliments!

And great work on Mplus! I actually use it as inspiration for Fridax since it Mplus already solves some of the problems that I need to overcome in the Fridax codebase.

I'm currently busy with creating a user-friendly 'API' for Fridax that enables anyone to start hacking Mono applications. I will push some code soon which lets you do, for example, the following:

    /* 
     *    namespace CompanyName.ProjectName {
     *
     *        class Settings {
     *
     *            public static ObfuscatedString secret = new ObfuscatedString("YDoAuB CgQodtB DidtA!");
     *
     *        }
     *
     *    }
     * 
     */

    // Construct a Fridax FridaxClass for the given `CompanyName.ProjectName.Settings` class.
    const settings = new FridaxClass('CompanyName.ProjectName.Settings')

    // Read the secret variable
    const secret = settings.getStaticField('staticSecretObfuscatedStringTest').toClass().getMethod('ToString').invoke().toString()
